### ISSUE TITLE
Does not build using icpc 15.0.2

### ISSUE THREAD

**Issue by sampollard** [narayanan2004/GraphMat#16]
When attempting to build on a 64-bit Linux Ubuntu distribution using the Intel 15 compiler

I get an error which begins with the following message:

```In file included from /usr/include/c++/5/sstream(813),
                 from src/Graph.cpp(36),
                 from src/GraphMatRuntime.cpp(45),
                 from src/PageRank.cpp(31):
/usr/include/c++/5/bits/stl_iterator_base_types.h(154): error: class "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>" has no member "iterator_category"
        typedef typename _Iterator::iterator_category iterator_category;
```

This does not change if I set ```export debug=1``` and then make.

**Comment by narayanan2004** [comment]
I am not able to reproduce this bug with icpc 15.0.3 or 16.0.3 on my machine. If possible, can you please upgrade to the latest icpc? 

I recommend trying the distributed_primitives_integration branch. That is where active development is happening now.

**Comment by sampollard** [comment]
Thank you for the advice.

I got it to compile by using icpc 17.0
